[workspace]
channels = ["conda-forge"]
platforms = [
    "linux-64",
    "osx-arm64",
    # "win-64"
]
preview = ["pixi-build"]
authors = ["rberga06 <78449715+RBerga06@users.noreply.github.com>"]

[dependencies]
pydual = { path = "." }

[pypi-dependencies]
numtype = { git = "https://github.com/numpy/numtype.git" }
build = ">=1.2.2.post1, <2"

[tasks]

[package]
name = "pydual"
version = "0.0.1"
readme = "README.md"
repository = "https://github.com/rberga06/pydual"

[package.build]
channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
uv = "*"
hatchling = "*"

[package.run-dependencies]
numpy = ">=2.3.1,<3"
