[project]
name = "pydual"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = ["numpy>=2.3.1,<3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pydual"]

[tool.pyright]
pythonVersion = "3.13"
