[project]
name = "pydual"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = ["numpy>=2.3.1,<3"]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["pydual.core"]

[tool.pyright]
pythonVersion = "3.13"
