name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pypi:
    name: Build PyPI package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build the project
        run: uv build -v --force-pep517 --wheel
      - name: Upload wheel as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: whl
          path: dist/*.whl
          retention-days: 1
  pypi-test:
    needs: pypi
    name: Test PyPI package contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - uses: actions/download-artifact@v4
        with:
          name: whl
      - name: Install project dependencies
        run: uv sync --no-install-project
      - name: Install project from wheel
        run: uv pip install *.whl
      - run: uv run python -c 'import pydual.core'
