name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build PyPI package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build the project
        run: uv build -v --force-pep517 --wheel
      - name: Upload wheel as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package wheel
          path: dist/*.whl
          retention-days: 1
