name: Docs
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - uses: prefix-dev/setup-pixi@v0.8.13
        with:
          pixi-version: latest
          cache: true
          environments: docs
      - run: pixi run mkdocs gh-deploy --force